# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-07 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cfee', models.IntegerField()),
                ('cduration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('esal', models.IntegerField()),
                ('eloc', models.CharField(max_length=20)),
                ('date_of_join', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20)),
                ('iloc', models.CharField(max_length=30)),
                ('ihead', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pcost', models.IntegerField()),
                ('pexpdate', models.DateField()),
                ('employeee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sage', models.IntegerField()),
                ('sfname', models.CharField(max_length=30)),
                ('scollege', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('tqual', models.CharField(max_length=20)),
                ('tmarritalstatus', models.CharField(max_length=20)),
                ('course', models.ManyToManyField(to='assapp.Course')),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assapp.Trainer'),
        ),
        migrations.AddField(
            model_name='course',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assapp.Employee'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assapp.Student'),
        ),
    ]
