# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-07 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='trainer',
            new_name='trainerr',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ManyToManyField(to='assapp.Trainer'),
        ),
    ]
